<?php

namespace Database\Seeders;

use App\Models\ShippingCharge;
use Illuminate\Database\Seeder;

class ShippingChargesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ShippingChargesRecords = [
            ['id'=>1,'country'=>'Afghanistan','shipping_charges'=>100,'status'=>1],
            ['id'=>2,'country'=>'Albania','shipping_charges'=>100,'status'=>1],
            ['id'=>3,'country'=>'Algeria','shipping_charges'=>100,'status'=>1],
            ['id'=>4,'country'=>'American Samoa','shipping_charges'=>100,'status'=>1],
            ['id'=>5,'country'=>'Andorra','shipping_charges'=>100,'status'=>1],
            ['id'=>6,'country'=>'Angola','shipping_charges'=>100,'status'=>1],
            ['id'=>7,'country'=>'Angola','shipping_charges'=>100,'status'=>1],
            ['id'=>8,'country'=>'Antarctica','shipping_charges'=>100,'status'=>1],
            ['id'=>9,'country'=>'Antigua and Barbuda','shipping_charges'=>100,'status'=>1],
            ['id'=>10,'country'=>'Argentina','shipping_charges'=>100,'status'=>1],
            ['id'=>11,'country'=>'Armenia','shipping_charges'=>100,'status'=>1],
            ['id'=>12,'country'=>'Aruba','shipping_charges'=>100,'status'=>1],
            ['id'=>13,'country'=>'Australia','shipping_charges'=>100,'status'=>1],
            ['id'=>14,'country'=>'Austria','shipping_charges'=>100,'status'=>1],
            ['id'=>15,'country'=>'Azerbaijan','shipping_charges'=>100,'status'=>1],
            ['id'=>16,'country'=>'Bahamas','shipping_charges'=>100,'status'=>1],
            ['id'=>17,'country'=>'Bahrain','shipping_charges'=>100,'status'=>1],
            ['id'=>18,'country'=>'Bangladesh','shipping_charges'=>100,'status'=>1],
            ['id'=>19,'country'=>'Barbados','shipping_charges'=>100,'status'=>1],
            ['id'=>20,'country'=>'Belarus','shipping_charges'=>100,'status'=>1],
            ['id'=>21,'country'=>'Belgium','shipping_charges'=>100,'status'=>1],
            ['id'=>22,'country'=>'Belize','shipping_charges'=>100,'status'=>1],
            ['id'=>23,'country'=>'Benin','shipping_charges'=>100,'status'=>1],
            ['id'=>24,'country'=>'Bermuda','shipping_charges'=>100,'status'=>1],
            ['id'=>25,'country'=>'Bhutan','shipping_charges'=>100,'status'=>1],
            ['id'=>26,'country'=>'Bolivia','shipping_charges'=>100,'status'=>1],
            ['id'=>27,'country'=>'Bosnia and Herzegovina','shipping_charges'=>100,'status'=>1],
            ['id'=>28,'country'=>'Botswana','shipping_charges'=>100,'status'=>1],
            ['id'=>29,'country'=>'Bouvet Island','shipping_charges'=>100,'status'=>1],
            ['id'=>30,'country'=>'Brazil','shipping_charges'=>100,'status'=>1],
            ['id'=>31,'country'=>'British Indian Ocean Territory','shipping_charges'=>100,'status'=>1],
            ['id'=>32,'country'=>'Brunei Darussalam','shipping_charges'=>100,'status'=>1],
            ['id'=>33,'country'=>'Bulgaria','shipping_charges'=>100,'status'=>1],
            ['id'=>34,'country'=>'Burkina Faso','shipping_charges'=>100,'status'=>1],
            ['id'=>35,'country'=>'Burundi','shipping_charges'=>100,'status'=>1],
            ['id'=>36,'country'=>'Cambodia','shipping_charges'=>100,'status'=>1],
            ['id'=>37,'country'=>'Cameroon','shipping_charges'=>100,'status'=>1],
            ['id'=>38,'country'=>'Canada','shipping_charges'=>100,'status'=>1],
            ['id'=>39,'country'=>'Cape Verde','shipping_charges'=>100,'status'=>1],
            ['id'=>40,'country'=>'Cayman Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>41,'country'=>'Central African Republic','shipping_charges'=>100,'status'=>1],
            ['id'=>42,'country'=>'Chad','shipping_charges'=>100,'status'=>1],
            ['id'=>43,'country'=>'Chile','shipping_charges'=>100,'status'=>1],
            ['id'=>44,'country'=>'China','shipping_charges'=>100,'status'=>1],
            ['id'=>45,'country'=>'Christmas Island','shipping_charges'=>100,'status'=>1],
            ['id'=>46,'country'=>'Cocos (Keeling) Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>47,'country'=>'Colombia','shipping_charges'=>100,'status'=>1],
            ['id'=>48,'country'=>'Comoros','shipping_charges'=>100,'status'=>1],
            ['id'=>49,'country'=>'Democratic Republic of the Congo','shipping_charges'=>100,'status'=>1],
            ['id'=>50,'country'=>'Republic of Congo','shipping_charges'=>100,'status'=>1],
            ['id'=>51,'country'=>'Cook Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>52,'country'=>'Costa Rica','shipping_charges'=>100,'status'=>1],
            ['id'=>53,'country'=>'Croatia (Hrvatska)','shipping_charges'=>100,'status'=>1],
            ['id'=>54,'country'=>'Cuba','shipping_charges'=>100,'status'=>1],
            ['id'=>55,'country'=>'Cyprus','shipping_charges'=>100,'status'=>1],
            ['id'=>56,'country'=>'Czech Republic','shipping_charges'=>100,'status'=>1],
            ['id'=>57,'country'=>'Denmark','shipping_charges'=>100,'status'=>1],
            ['id'=>58,'country'=>'Djibouti','shipping_charges'=>100,'status'=>1],
            ['id'=>59,'country'=>'Dominica','shipping_charges'=>100,'status'=>1],
            ['id'=>60,'country'=>'Dominican Republic','shipping_charges'=>100,'status'=>1],
            ['id'=>61,'country'=>'East Timor','shipping_charges'=>100,'status'=>1],
            ['id'=>62,'country'=>'Ecuador','shipping_charges'=>100,'status'=>1],
            ['id'=>63,'country'=>'Egypt','shipping_charges'=>100,'status'=>1],
            ['id'=>64,'country'=>'El Salvador','shipping_charges'=>100,'status'=>1],
            ['id'=>65,'country'=>'Equatorial Guinea','shipping_charges'=>100,'status'=>1],
            ['id'=>66,'country'=>'Eritrea','shipping_charges'=>100,'status'=>1],
            ['id'=>67,'country'=>'Estonia','shipping_charges'=>100,'status'=>1],
            ['id'=>68,'country'=>'Ethiopia','shipping_charges'=>100,'status'=>1],
            ['id'=>69,'country'=>'Falkland Islands (Malvinas)','shipping_charges'=>100,'status'=>1],
            ['id'=>70,'country'=>'Faroe Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>71,'country'=>'Fiji','shipping_charges'=>100,'status'=>1],
            ['id'=>72,'country'=>'Finland','shipping_charges'=>100,'status'=>1],
            ['id'=>73,'country'=>'France','shipping_charges'=>100,'status'=>1],
            ['id'=>74,'country'=>'France, Metropolitan','shipping_charges'=>100,'status'=>1],
            ['id'=>75,'country'=>'French Guiana','shipping_charges'=>100,'status'=>1],
            ['id'=>76,'country'=>'French Polynesia','shipping_charges'=>100,'status'=>1],
            ['id'=>77,'country'=>'French Southern Territories','shipping_charges'=>100,'status'=>1],
            ['id'=>78,'country'=>'Gabon','shipping_charges'=>100,'status'=>1],
            ['id'=>79,'country'=>'Gambia','shipping_charges'=>100,'status'=>1],
            ['id'=>80,'country'=>'Georgia','shipping_charges'=>100,'status'=>1],
            ['id'=>81,'country'=>'Germany','shipping_charges'=>100,'status'=>1],
            ['id'=>82,'country'=>'Ghana','shipping_charges'=>100,'status'=>1],
            ['id'=>83,'country'=>'Gibraltar','shipping_charges'=>100,'status'=>1],
            ['id'=>84,'country'=>'Guernsey','shipping_charges'=>100,'status'=>1],
            ['id'=>85,'country'=>'Greece','shipping_charges'=>100,'status'=>1],
            ['id'=>86,'country'=>'Greenland','shipping_charges'=>100,'status'=>1],
            ['id'=>87,'country'=>'Grenada','shipping_charges'=>100,'status'=>1],
            ['id'=>88,'country'=>'Guadeloupe','shipping_charges'=>100,'status'=>1],
            ['id'=>89,'country'=>'Guam','shipping_charges'=>100,'status'=>1],
            ['id'=>90,'country'=>'Guatemala','shipping_charges'=>100,'status'=>1],
            ['id'=>91,'country'=>'Guinea','shipping_charges'=>100,'status'=>1],
            ['id'=>92,'country'=>'Guinea-Bissau','shipping_charges'=>100,'status'=>1],
            ['id'=>93,'country'=>'Guyana','shipping_charges'=>100,'status'=>1],
            ['id'=>94,'country'=>'Haiti','shipping_charges'=>100,'status'=>1],
            ['id'=>95,'country'=>'Heard and Mc Donald Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>96,'country'=>'Honduras','shipping_charges'=>100,'status'=>1],
            ['id'=>97,'country'=>'Hong Kong','shipping_charges'=>100,'status'=>1],
            ['id'=>98,'country'=>'Hungary','shipping_charges'=>100,'status'=>1],
            ['id'=>99,'country'=>'Iceland','shipping_charges'=>100,'status'=>1],
            ['id'=>100,'country'=>'India','shipping_charges'=>100,'status'=>1],
            ['id'=>101,'country'=>'Isle of Man','shipping_charges'=>100,'status'=>1],
            ['id'=>102,'country'=>'Indonesia','shipping_charges'=>100,'status'=>1],
            ['id'=>103,'country'=>'Iran (Islamic Republic of)','shipping_charges'=>100,'status'=>1],
            ['id'=>104,'country'=>'Iraq','shipping_charges'=>100,'status'=>1],
            ['id'=>105,'country'=>'Ireland','shipping_charges'=>100,'status'=>1],
            ['id'=>106,'country'=>'Israel','shipping_charges'=>100,'status'=>1],
            ['id'=>107,'country'=>'Italy','shipping_charges'=>100,'status'=>1],
            ['id'=>108,'country'=>'Ivory Coast','shipping_charges'=>100,'status'=>1],
            ['id'=>109,'country'=>'Jersey','shipping_charges'=>100,'status'=>1],
            ['id'=>110,'country'=>'Jamaica','shipping_charges'=>100,'status'=>1],
            ['id'=>111,'country'=>'Japan','shipping_charges'=>100,'status'=>1],
            ['id'=>112,'country'=>'Jordan','shipping_charges'=>100,'status'=>1],
            ['id'=>113,'country'=>'Kazakhstan','shipping_charges'=>100,'status'=>1],
            ['id'=>114,'country'=>'Kenya','shipping_charges'=>100,'status'=>1],
            ['id'=>115,'country'=>'Kiribati','shipping_charges'=>100,'status'=>1],
            ['id'=>116,'country'=>'North Korea','shipping_charges'=>100,'status'=>1],
            ['id'=>117,'country'=>'Korea','shipping_charges'=>100,'status'=>1],
            ['id'=>118,'country'=>'Kosovo','shipping_charges'=>100,'status'=>1],
            ['id'=>119,'country'=>'Kuwait','shipping_charges'=>100,'status'=>1],
            ['id'=>120,'country'=>'Kyrgyzstan','shipping_charges'=>100,'status'=>1],
            ['id'=>121,'country'=>'Lao','shipping_charges'=>100,'status'=>1],
            ['id'=>122,'country'=>'Latvia','shipping_charges'=>100,'status'=>1],
            ['id'=>123,'country'=>'Lebanon','shipping_charges'=>100,'status'=>1],
            ['id'=>124,'country'=>'Lesotho','shipping_charges'=>100,'status'=>1],
            ['id'=>125,'country'=>'Liberia','shipping_charges'=>100,'status'=>1],
            ['id'=>126,'country'=>'Libyan Arab Jamahiriya','shipping_charges'=>100,'status'=>1],
            ['id'=>127,'country'=>'Liechtenstein','shipping_charges'=>100,'status'=>1],
            ['id'=>128,'country'=>'Lithuania','shipping_charges'=>100,'status'=>1],
            ['id'=>129,'country'=>'Luxembourg','shipping_charges'=>100,'status'=>1],
            ['id'=>130,'country'=>'Macau','shipping_charges'=>100,'status'=>1],
            ['id'=>131,'country'=>'North Macedonia','shipping_charges'=>100,'status'=>1],
            ['id'=>132,'country'=>'Madagascar','shipping_charges'=>100,'status'=>1],
            ['id'=>133,'country'=>'Malawi','shipping_charges'=>100,'status'=>1],
            ['id'=>134,'country'=>'Malaysia','shipping_charges'=>100,'status'=>1],
            ['id'=>135,'country'=>'Maldives','shipping_charges'=>100,'status'=>1],
            ['id'=>136,'country'=>'Mali','shipping_charges'=>100,'status'=>1],
            ['id'=>137,'country'=>'Malta','shipping_charges'=>100,'status'=>1],
            ['id'=>138,'country'=>'Marshall Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>139,'country'=>'Martinique','shipping_charges'=>100,'status'=>1],
            ['id'=>140,'country'=>'Mauritania','shipping_charges'=>100,'status'=>1],
            ['id'=>141,'country'=>'Mauritius','shipping_charges'=>100,'status'=>1],
            ['id'=>142,'country'=>'Mayotte','shipping_charges'=>100,'status'=>1],
            ['id'=>143,'country'=>'Mexico','shipping_charges'=>100,'status'=>1],
            ['id'=>144,'country'=>'Micronesia, Federated States of','shipping_charges'=>100,'status'=>1],
            ['id'=>145,'country'=>'Moldova, Republic of','shipping_charges'=>100,'status'=>1],
            ['id'=>146,'country'=>'Monaco','shipping_charges'=>100,'status'=>1],
            ['id'=>147,'country'=>'Mongolia','shipping_charges'=>100,'status'=>1],
            ['id'=>148,'country'=>'Montenegro','shipping_charges'=>100,'status'=>1],
            ['id'=>149,'country'=>'Montserrat','shipping_charges'=>100,'status'=>1],
            ['id'=>150,'country'=>'Morocco','shipping_charges'=>100,'status'=>1],
            ['id'=>151,'country'=>'Mozambique','shipping_charges'=>100,'status'=>1],
            ['id'=>152,'country'=>'Myanmar','shipping_charges'=>100,'status'=>1],
            ['id'=>153,'country'=>'Namibia','shipping_charges'=>100,'status'=>1],
            ['id'=>154,'country'=>'Nauru','shipping_charges'=>100,'status'=>1],
            ['id'=>155,'country'=>'Nepal','shipping_charges'=>100,'status'=>1],
            ['id'=>156,'country'=>'Netherlands','shipping_charges'=>100,'status'=>1],
            ['id'=>157,'country'=>'Netherlands Antilles','shipping_charges'=>100,'status'=>1],
            ['id'=>158,'country'=>'New Caledonia','shipping_charges'=>100,'status'=>1],
            ['id'=>159,'country'=>'New Zealand','shipping_charges'=>100,'status'=>1],
            ['id'=>160,'country'=>'Nicaragua','shipping_charges'=>100,'status'=>1],
            ['id'=>161,'country'=>'Niger','shipping_charges'=>100,'status'=>1],
            ['id'=>162,'country'=>'Nigeria','shipping_charges'=>100,'status'=>1],
            ['id'=>163,'country'=>'Niue','shipping_charges'=>100,'status'=>1],
            ['id'=>164,'country'=>'Norfolk Island','shipping_charges'=>100,'status'=>1],
            ['id'=>165,'country'=>'Northern Mariana Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>166,'country'=>'Norway','shipping_charges'=>100,'status'=>1],
            ['id'=>167,'country'=>'Oman','shipping_charges'=>100,'status'=>1],
            ['id'=>168,'country'=>'Pakistan','shipping_charges'=>100,'status'=>1],
            ['id'=>169,'country'=>'Palau','shipping_charges'=>100,'status'=>1],
            ['id'=>170,'country'=>'Palestine','shipping_charges'=>100,'status'=>1],
            ['id'=>171,'country'=>'Panama','shipping_charges'=>100,'status'=>1],
            ['id'=>172,'country'=>'Papua New Guinea','shipping_charges'=>100,'status'=>1],
            ['id'=>173,'country'=>'Paraguay','shipping_charges'=>100,'status'=>1],
            ['id'=>174,'country'=>'Philippines','shipping_charges'=>100,'status'=>1],
            ['id'=>175,'country'=>'Pitcairn','shipping_charges'=>100,'status'=>1],
            ['id'=>176,'country'=>'Poland','shipping_charges'=>100,'status'=>1],
            ['id'=>177,'country'=>'Portugal','shipping_charges'=>100,'status'=>1],
            ['id'=>178,'country'=>'Puerto Rico','shipping_charges'=>100,'status'=>1],
            ['id'=>179,'country'=>'Qatar','shipping_charges'=>100,'status'=>1],
            ['id'=>180,'country'=>'Reunion','shipping_charges'=>100,'status'=>1],
            ['id'=>181,'country'=>'Romania','shipping_charges'=>100,'status'=>1],
            ['id'=>182,'country'=>'Body','shipping_charges'=>100,'status'=>1],
            ['id'=>183,'country'=>'Russian Federation','shipping_charges'=>100,'status'=>1],
            ['id'=>184,'country'=>'Rwanda','shipping_charges'=>100,'status'=>1],
            ['id'=>185,'country'=>'Saint Kitts and Nevis','shipping_charges'=>100,'status'=>1],
            ['id'=>186,'country'=>'Saint Lucia','shipping_charges'=>100,'status'=>1],
            ['id'=>187,'country'=>'Saint Vincent and the Grenadines','shipping_charges'=>100,'status'=>1],
            ['id'=>188,'country'=>'Samoa','shipping_charges'=>100,'status'=>1],
            ['id'=>189,'country'=>'San Marino','shipping_charges'=>100,'status'=>1],
            ['id'=>190,'country'=>'Sao Tome and Principe','shipping_charges'=>100,'status'=>1],
            ['id'=>191,'country'=>'Saudi Arabia','shipping_charges'=>100,'status'=>1],
            ['id'=>192,'country'=>'Senegal','shipping_charges'=>100,'status'=>1],
            ['id'=>193,'country'=>'Serbia','shipping_charges'=>100,'status'=>1],
            ['id'=>194,'country'=>'Seychelles','shipping_charges'=>100,'status'=>1],
            ['id'=>195,'country'=>'Sierra Leone','shipping_charges'=>100,'status'=>1],
            ['id'=>196,'country'=>'Singapore','shipping_charges'=>100,'status'=>1],
            ['id'=>197,'country'=>'Slovakia','shipping_charges'=>100,'status'=>1],
            ['id'=>198,'country'=>'Slovenia','shipping_charges'=>100,'status'=>1],
            ['id'=>199,'country'=>'Solomon Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>200,'country'=>'Somalia','shipping_charges'=>100,'status'=>1],
            ['id'=>201,'country'=>'South Africa','shipping_charges'=>100,'status'=>1],
            ['id'=>202,'country'=>'South Georgia South Sandwich Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>203,'country'=>'South Sudan','shipping_charges'=>100,'status'=>1],
            ['id'=>204,'country'=>'Spain','shipping_charges'=>100,'status'=>1],
            ['id'=>205,'country'=>'Sri Lanka','shipping_charges'=>100,'status'=>1],
            ['id'=>206,'country'=>'St. Helena','shipping_charges'=>100,'status'=>1],
            ['id'=>207,'country'=>'St. Pierre and Miquelon','shipping_charges'=>100,'status'=>1],
            ['id'=>208,'country'=>'Sudan','shipping_charges'=>100,'status'=>1],
            ['id'=>209,'country'=>'Suriname','shipping_charges'=>100,'status'=>1],
            ['id'=>210,'country'=>'Svalbard and Jan Mayen Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>211,'country'=>'Swaziland','shipping_charges'=>100,'status'=>1],
            ['id'=>212,'country'=>'Sweden','shipping_charges'=>100,'status'=>1],
            ['id'=>213,'country'=>'Switzerland','shipping_charges'=>100,'status'=>1],
            ['id'=>214,'country'=>'Syrian Arab Republic','shipping_charges'=>100,'status'=>1],
            ['id'=>215,'country'=>'Taiwan','shipping_charges'=>100,'status'=>1],
            ['id'=>216,'country'=>'Tajikistan','shipping_charges'=>100,'status'=>1],
            ['id'=>217,'country'=>'Tanzania, United Republic of','shipping_charges'=>100,'status'=>1],
            ['id'=>218,'country'=>'Thailand','shipping_charges'=>100,'status'=>1],
            ['id'=>219,'country'=>'Togo','shipping_charges'=>100,'status'=>1],
            ['id'=>220,'country'=>'Tokelau','shipping_charges'=>100,'status'=>1],
            ['id'=>221,'country'=>'Tonga','shipping_charges'=>100,'status'=>1],
            ['id'=>222,'country'=>'Trinidad and Tobago','shipping_charges'=>100,'status'=>1],
            ['id'=>223,'country'=>'Tunisia','shipping_charges'=>100,'status'=>1],
            ['id'=>224,'country'=>'Turkey','shipping_charges'=>100,'status'=>1],
            ['id'=>225,'country'=>'Turkmenistan','shipping_charges'=>100,'status'=>1],
            ['id'=>226,'country'=>'Turks and Caicos Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>227,'country'=>'Tuvalu','shipping_charges'=>100,'status'=>1],
            ['id'=>228,'country'=>'Uganda','shipping_charges'=>100,'status'=>1],
            ['id'=>229,'country'=>'Ukraine','shipping_charges'=>100,'status'=>1],
            ['id'=>230,'country'=>'United Arab Emirates','shipping_charges'=>100,'status'=>1],
            ['id'=>231,'country'=>'United Kingdom','shipping_charges'=>100,'status'=>1],
            ['id'=>232,'country'=>'United States','shipping_charges'=>100,'status'=>1],
            ['id'=>233,'country'=>'United States minor outlying islands','shipping_charges'=>100,'status'=>1],
            ['id'=>234,'country'=>'Uruguay','shipping_charges'=>100,'status'=>1],
            ['id'=>235,'country'=>'Uzbekistan','shipping_charges'=>100,'status'=>1],
            ['id'=>236,'country'=>'Vanuatu','shipping_charges'=>100,'status'=>1],
            ['id'=>237,'country'=>'Vatican City State','shipping_charges'=>100,'status'=>1],
            ['id'=>238,'country'=>'Venezuela','shipping_charges'=>100,'status'=>1],
            ['id'=>239,'country'=>'Vietnam','shipping_charges'=>100,'status'=>1],
            ['id'=>240,'country'=>'Virgin Islands (British)','shipping_charges'=>100,'status'=>1],
            ['id'=>241,'country'=>'Virgin Islands (U.S.)','shipping_charges'=>100,'status'=>1],
            ['id'=>242,'country'=>'Wallis and Futuna Islands','shipping_charges'=>100,'status'=>1],
            ['id'=>243,'country'=>'Western Sahara','shipping_charges'=>100,'status'=>1],
            ['id'=>244,'country'=>'Yemen','shipping_charges'=>100,'status'=>1],
            ['id'=>245,'country'=>'Zambia','shipping_charges'=>100,'status'=>1],
            ['id'=>246,'country'=>'Zimbabwe','shipping_charges'=>100,'status'=>1],
    ];

    ShippingCharge::insert($ShippingChargesRecords);
    }
}
